### ISSUE TITLE
东东玩家执行失败

### ISSUE THREAD

**Issue by tmsdy** [jinboyigu/lazy_script#11]
我手动在app.js中添加了东东玩家的任务后，执行失败
[2021-09-26 16:27:36.543] [东东玩家] do start: 4.276s
    at Function.getEncryptBody (/home/runner/work/lazy_script/lazy_script/src/jd/base/SmashUtilsTemplate.js:69:24)
    at /home/runner/work/lazy_script/lazy_script/src/jd/base/SmashUtilsTemplate.js:148:42
    at Api.context.<computed> [as doFormBody] (/home/runner/work/lazy_script/lazy_script/src/lib/common.js:173:68)
    at api.<computed> (/home/runner/work/lazy_script/lazy_script/src/jd/base/index.js:220:51)
    at _do (/home/runner/work/lazy_script/lazy_script/src/jd/base/index.js:177:18)
    at Function.doApi (/home/runner/work/lazy_script/lazy_script/src/jd/base/index.js:192:12)
    at option.firstFn (/home/runner/work/lazy_script/lazy_script/src/jd/base/template.js:116:58)
    at doLoop (/home/runner/work/lazy_script/lazy_script/src/jd/base/index.js:154:28)
    at Function.loopCall (/home/runner/work/lazy_script/lazy_script/src/jd/base/index.js:148:11)
    at async _doTask (/home/runner/work/lazy_script/lazy_script/src/jd/base/template.js:120:13)
    at async Function.doMain (/home/runner/work/lazy_script/lazy_script/src/jd/base/template.js:99:5)
    at async init (/home/runner/work/lazy_script/lazy_script/src/jd/base/index.js:296:7)
    at async _do (/home/runner/work/lazy_script/lazy_script/src/jd/base/index.js:284:5)
    at async Function.loopInit (/home/runner/work/lazy_script/lazy_script/src/jd/base/index.js:278:5)
    at async Function.start (/home/runner/work/lazy_script/lazy_script/src/jd/base/index.js:232:7)
    at async doRun (/home/runner/work/lazy_script/lazy_script/src/api.js:40:14)

**Comment by jinboyigu** [comment]
如果东东玩家脚本提示活动火爆了, 需要手动抓包获取token模拟请求才行, 具体如下

- 需要在手机上抓包,  用Charles在 funny_collectScore 的请求打断点
- 点那个开通品牌会员多次, 收集几十个请求(粗略估计是40个请求就可以做完一天任务)后导出到 `charles/chlsj/jd/funny_collectScore/${this.currentCookieTimes}.chlsj` 中, 导出后记得重新打开抓包软件并取消断点
- 然后再手动执行脚本就行, 如果还需要再加载数据, 需要重新抓包覆盖源文件并手动重置相应目录的localData.json的`ssIndex`为0
- 抓包的token有效期估计不超过12小时

如果觉得繁琐就先用 `src/618/Funny.js` 试试看, 如果火爆了, **就必须抓当前账号的包模拟token才行, 这是目前唯一试出的方法**

**Comment by jinboyigu** [comment]
这种方法不能用多, 用多号也是会火爆, 所以先关掉吧, 目前没有好的脚本方法

**Comment by tmsdy** [comment]
有没有办法直接提取smashUtils.get_risk_result这个方法出来实时计算log
