### ISSUE TITLE
为啥static async beforeRequest(api) 一直报错

### ISSUE THREAD

**Issue by MavonCmc** [jinboyigu/lazy_script#16]
Uncaught Exception...
Error: spawn touch ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:274:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)

**Comment by jinboyigu** [comment]
是 node 版本不对吗? 建议 14+

**Comment by MavonCmc** [comment]
v14.18.1

**Comment by jinboyigu** [comment]
运行哪个脚本报的错误?
