### ISSUE TITLE
关于服务器运行脚本

### ISSUE THREAD

**Issue by leeyiding** [jinboyigu/lazy_script#3]
我想在本地Linux服务器运行脚本，已安装nodejs环境，请问cookie如何填写

**Comment by jinboyigu** [comment]
根目录新增 '.env.local'文件
内容格式为
`key=value`

下完依赖后执行
`npm run dev`

**Comment by leeyiding** [comment]
添加Cookie后 执行`npm run dev`报错
```
> lazy_script@1.0.0 dev /home/pi/lazy_script
> node src/dev.js

Tail starting...
filename: /home/pi/lazy_script/logs/app.log.2020-09-17
encoding: utf-8
filesystem.watch present? true
useWatchFile: false
fromBeginning: false
watch strategy: watch
/home/pi/lazy_script/src/jd/newPet/index.js:6
  static scriptName = 'Pet';
                    ^

SyntaxError: Unexpected token =
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/pi/lazy_script/src/app.js:16:13)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
(node:8861) UnhandledPromiseRejectionWarning: Error: Command failed: node src/app.js
/home/pi/lazy_script/src/jd/newPet/index.js:6
  static scriptName = 'Pet';
                    ^

SyntaxError: Unexpected token =
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/pi/lazy_script/src/app.js:16:13)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)

    at checkExecSyncError (child_process.js:629:11)
    at execSync (child_process.js:666:13)
    at start (/home/pi/lazy_script/src/dev.js:39:10)
    at Object.<anonymous> (/home/pi/lazy_script/src/dev.js:42:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
(node:8861) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:8861) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by jinboyigu** [comment]
贴一下node的版本

**Comment by leeyiding** [comment]
```
node -v                                                         
v10.21.0
npm -v 
6.14.8
```

**Comment by jinboyigu** [comment]
因为用了 static class fields, 用12+的版本吧 

https://node.green/#ESNEXT-candidate--stage-3--instance-class-fields

**Comment by leeyiding** [comment]
感谢回复 将nodejs更新至V12.18.4后，报错消失
```
> lazy_script@1.0.0 dev /home/pi/lazy_script
> node src/dev.js

Tail starting...
filename: /home/pi/lazy_script/logs/app.log.2020-09-18
encoding: utf-8
filesystem.watch present? true
useWatchFile: false
fromBeginning: false
watch strategy: watch

app.js 运行结果:
发送成功
```
对于以上结果有几点疑问和建议
1. 终端运行结果输出为空白，查看`app.log.2020-09-18`文件，内容也为空白
2. 脚本执行结束后，需要手动`Ctrl+C`结束进程
3. 是否可以添加一个server酱读取本地环境变量的功能

**Comment by jinboyigu** [comment]
> 终端运行结果输出为空白，查看app.log.2020-09-18文件，内容也为空白

定时执行的, 特定时间执行哪个脚本的, 你可以看看app.js, 根据你需要进行更改

> 脚本执行结束后，需要手动Ctrl+C结束进程

这个应该是没输出结果导致的, 后面再改下

> 是否可以添加一个server酱读取本地环境变量的功能

这个是要怎么读取? 在.env.local添加 SEVER_CHAN_KEY 即可发送app.log日志, 具体的变量定义可以参考 workflows/schedule.yaml
